import type { Metadata } from 'next'
import './globals.css'
import Burger from "@/components/menu/burger";
import Header from "@/components/menu/header";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Burger />
        {children}
      </body>
    </html>
  )
}
